---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      include_vars: vars/main.yml

    - name: Check File System Content
      include_tasks: "../common/tasks/files.yml"

    - name: Assert homeshick repository was installed
      assert:
        that:
          - homeshick_install.stat.exists
          - homeshick_install.stat.pw_name == homeshick_user
        msg: "Homeshick repository must exist"
    - name: Assert the user dotfiles were installed
      assert:
        that:
          - dotfiles_install.stat.exists
          - dotfiles_install.stat.pw_name == homeshick_user
        msg: "Dotfiles repository must exist"
    - name: Assert the user .bashrc was symlinked, and is readable
      assert:
        that:
          - bashrc_symlink.stat.islnk
          - bashrc_symlink.stat.readable
        msg: "User .bashrc must be a readable symlink"
