---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml

    - name: Check File System Content
      ansible.builtin.include_tasks: "../common/tasks/files.yml"

    - name: Assert homeshick repository was installed
      ansible.builtin.assert:
        that:
          - homeshick_install.stat.exists
          - homeshick_install.stat.pw_name == homeshick_user
        msg: "Homeshick repository must exist"

    - name: Assert the user dotfiles were installed
      ansible.builtin.assert:
        that:
          - dotfiles_install.stat.exists
          - dotfiles_install.stat.pw_name == homeshick_user
        msg: "Dotfiles repository must exist"

    - name: Assert the user .bashrc was NOT symlinked (existing file)
      ansible.builtin.assert:
        that:
          - not bashrc_symlink.stat.islnk
          - bashrc_symlink.stat.readable
        msg: "User .bashrc must be a readable file (not a symlink)"
